name: AI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 720

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      timeout-minutes: 720
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
      timeout-minutes: 720
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      timeout-minutes: 720
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        timeout-minutes: 720
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      timeout-minutes: 720
    - name: Firewall for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      timeout-minutes: 720
    - name: Allow RDP Property from Regdit
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      timeout-minutes: 720
    - name: Assign User
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Prime456$" -Force)
      timeout-minutes: 720
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
      timeout-minutes: 720
    - name: Download Timeout Script
      run: Invoke-WebRequest https://raw.githubusercontent.com/ptr15/win/main/timeout.ps1 -OutFile timeout.ps1
      timeout-minutes: 720
    - name: Keep Alive
      run: ./timeout.ps1
      timeout-minutes: 720
 
